### ISSUE TITLE
[Bug] Callback URL sent to wallet `http` should be `https`

### ISSUE THREAD

**Issue by willemneal** [AhaLabs/close-up#13]
Here is an example URL from wallet:

https://wallet.testnet.near.org/sign?transactions=CwAAAGV2ZS50ZXN0bmV0AHtU7ZWEsSYTzp7kI6bY7lK%2FGM1YhJcNv5tkMKPlcn2wyQAAAAAAAAASAAAAY2F0dHkudGVuay50ZXN0bmV0VxnrOiAPFukY1fq7ALVzOlRHs1X7r7v2jbJtAUMqL44BAAAAAgwAAABuZnRfbWludF9vbmUCAAAAe30A4FfrSBsAAAAAAMaRzdimjPYEAAAAAAA%3D&callbackUrl=http%3A%2F%2Fraen.dev%2Fadmin%2F%3FtransactionHashes%3DF4XGFgm1Hd9jZQLJ4CVepfH5ErdVyNdRBfbeZH4H93XK%23%2Fcatty.tenk.testnet%2FNftMintOne%3Fdata%3D%25257B%252522args%252522%25253A%25257B%25257D%25252C%252522options%252522%25253A%25257B%252522attachedDeposit%252522%25253A%2525226000000000000000000000000%252522%25252C%252522gas%252522%25253A%25252230000000000000%252522%25257D%25257D

`callbackUrl=http` --> `callbackUrl=https`

**Comment by chadoh** [comment]
I don't see this, nor do we have any code that sets this (it is set automatically by near-api-js). When I am redirected to NEAR Wallet, here's what I see:

> ```https://wallet.testnet.near.org/sign?transactions=DAAAAGNoYWQudGVzdG5ldAAQeiZuXiG3qNB4LT6%2BWtM%2BEhR77OGAhs%2Bb0ZiFvjXH4UVyEhGpUwAADwAAAHYyLnRlbmsudGVzdG5ldAhSH6i1m2CRnKaeumx%2Bt5NxJEcWr4ca59502K5JXJBSAQAAAAINAAAAbmZ0X21pbnRfbWFueQkAAAB7Im51bSI6MX0A4FfrSBsAAAAAAELbmZ03hKcBAAAAAAA%3D&callbackUrl=https%3A%2F%2Fraen.dev%2Fadmin%2F%23%2Fv2.tenk.testnet%2FNftMintMany%3Fdata%3D%25257B%252522args%252522%25253A%25257B%252522num%252522%25253A1%25257D%25252C%252522options%252522%25253A%25257B%252522attachedDeposit%252522%25253A%2525222000000000000000000000000%252522%25252C%252522gas%252522%25253A%25252230000000000000%252522%25257D%25257D```
