### ISSUE TITLE
[feat] Store contracts with hash and redownload if state's contract hash differs

### ISSUE THREAD

**Issue by willemneal** [AhaLabs/close-up#33]

**Comment by chadoh** [comment]
Currently accomplishing this with [fast-deep-equal](https://www.npmtrends.com/check-equal-vs-deep-equal-vs-dequal-vs-fast-deep-equal-vs-fast-equals-vs-lite-deep-equal-vs-lodash.isequal) on [this line](https://github.com/raendev/admin/blob/86a99a6d368b401a43c90ead34b6530de199b8eb/src/hooks/useNear.ts#L67). Feel free to re-open this issue if you think there's a benefit to using the hash approach, and please explain such benefits.

**Comment by chadoh** [comment]
hmm, should maybe switch to `lodash.isEqual`, though https://www.measurethat.net/Benchmarks/ShowResult/307283

**Comment by willemneal** [comment]
I should have included more in my description.  We can use the RPC call to get the account's state, which includes the contract hash.  Then if use local storage to store that contract bytes by accountId + hash.  Then the following times we just need to check the hash to decide to download.

This should be extracted out into it's own library, e.i. the fetch command.

I'll let this be closed for now since the current solution works.
